### ISSUE TITLE
One-off bug?

### ISSUE THREAD

**Issue by lxkain** [kylebgorman/pynini#18]
Using openfst 1.7.5, and pynini 2.0.9.post2, if I do:

```
words='you say potato'.split()

word_table = ni.SymbolTable()
word_table.add_symbol('<ε>')  # empty symbol at index 0
print(word_table.num_symbols())

for sym in words:
    word_table.add_symbol(sym)
    print(word_table.num_symbols())
```

I see output:

```
1
2
2
3
```

**Comment by kylebgorman** [comment]
Thanks for very clear report; looks suspicious. Will investigate: would
probably be an issue with OpenFst itself. There has been some recent churn
in the symbol table object.

**Comment by lxkain** [comment]
Should I try with openfst 1.7.4?

**Comment by kylebgorman** [comment]
You could but I’m not sure it’d help track this down.

Unrelatedly almost all of this stuff is on Conda-Forge as of yesterday.

**Comment by lxkain** [comment]
I tried installing from conda-forge on a brand-new anaconda python 3.7 install. After about one hour I hit CTRL-C :(

**Comment by kylebgorman** [comment]
Good news, this doesn't replicate at (internal) HEAD for me so we must have fixed it or, IDK, something else is going on. Will put out another version bump before too long.

**Comment by lxkain** [comment]
This bug persists in version 2.1.0 :( 

Incidentally, the conda-forge install works now!

**Comment by kylebgorman** [comment]
Would you be willing to take a look? I absolutely cannot reproduce this as
I do not own any Macs and it doesn't seem to occur anywhere else.

**Comment by lxkain** [comment]
I ran this in an ubuntu VM and indeed it works fine! Very puzzling. I'm not sure if I will have the time to debug this, and I can use Linux as a work-around for the time being.

**Comment by lxkain** [comment]
```CFLAGS="-stdlib=libc++ -mmacosx-version-min=10.7" python setup.py install```

fixes this
