### ISSUE TITLE
[input|output]_token_type -> token_type

### ISSUE THREAD

**Issue by lxkain** [kylebgorman/pynini#22]
the following code used to work, in version 2.0.7 under OSX, to construct a pronunciation FST:

```ni.t(p, w, 0, input_token_type=phoneme_table, output_token_type=word_table)```

However, in version 2.1.0 it appears that keywords [input|output]_token_type were replaced by a single token_type. How can input and output be set differently? (Maybe construct acceptors first?)

**Comment by kylebgorman** [comment]
Yeah, that's what I'd recommend. You don't really incur any cost for that
extra code since it was doing that behind the scenes anyways.

**Comment by lxkain** [comment]
OK, that seems to work, but strings are now not showing up properly in jupyter notebooks.

**Comment by lxkain** [comment]
Unfortunately, drawing transducers doesn't seem to work, even with

```    fst.draw('tmp.dot', portrait=True, isymbols=fst.input_symbols(), osymbols=fst.output_symbols())```

**Comment by kylebgorman** [comment]
What are you getting instead?

**Comment by lxkain** [comment]
The integer indeces

**Comment by kylebgorman** [comment]
Oh, that's expected with the new revision. We are not longer automatically
attaching symbol tables as of 2.1.0 (see NEWS).

**Comment by lxkain** [comment]
I see. I'm assuming that's because the table was copied and not linked to. It does mean that the shortest way to have jupyter notebook/lab output is now

```
a = ni.acceptor("you say potato", token_type=word_table)  # space delimits tokens
a.set_input_symbols(word_table)
a
```

which is unfortunately a little wordy. I'll bypass this by creating my own FST that does attach symbol tables. Thank you for the clarification!

**Comment by lxkain** [comment]
For other folk who may wonder, for transducers it would now be:

```
t = ni.transducer(ni.acceptor('you', token_type=word_table), 
              ni.acceptor('j u', token_type=phoneme_table))
t.set_input_symbols(word_table)
t.set_output_symbols(phoneme_table)
```

**Comment by lxkain** [comment]
If tables were copied previously, then I can see that operations like:

```
        tmp = (ni.t(ni.a(p, token_type=self.phoneme_table),
                    ni.a(w, token_type=self.word_table),
                    0
                    ) for w, p in self.pronunciation.items())  # generator
        fst = ni.union(*tmp)
        fst.set_input_symbols(self.phoneme_table)
        fst.set_output_symbols(self.word_table)
```

are definitely benefiting from this decision, even if simple situations become more wordy. Although I flag that would be about copy vs. link may be immensely useful.

**Comment by kylebgorman** [comment]
Yes, I think the generalization is:

* any in-place/destructive/mutation operation that doesn't manipulate
symbol tables preserves them
* any constructive operation which takes a single FST input copies the
symbol table of the input FST (and copying symbol tables is constant-time)
* any constructive operation which takes two or more FST inputs first
confirms that any symbol tables present are "compatible" along the
appropriate dimensions, and then copies them to the output FST

K
