### ISSUE TITLE
Provide compiled python wheels including OpenFst dependencies on Linux

### ISSUE THREAD

**Issue by PierreAndreNoel** [kylebgorman/pynini#27]
The contribution promised [here](https://github.com/kylebgorman/pynini/issues/19#issuecomment-626813218) is now available at https://github.com/ElementAI/build-pynini-wheels

@kylebgorman , please let me know if you have trouble making it work and/or need further assistance.

**Comment by kylebgorman** [comment]
Thanks, I'll see if we can link to this as a third-party solution.

**Comment by daanzu** [comment]
@kylebgorman I updated the Docker-based build for wheels in https://github.com/ElementAI/build-pynini-wheels/pull/3. Although I didn't know how to run the current set of tests, the wheels build and seem to work. Please let me know if you want more info on building or publishing for PyPI.

**Comment by kylebgorman** [comment]
Thanks again. I had trouble with the Docker setup for that, which is the only reason I haven't published it yet-I literally could not get it working locally. I'll try again shortly and ping you with any issues I encounter.

**Comment by fquirin** [comment]
Hello everyone :-)
I'm currently building the new [STT WebSocket Server](https://github.com/SEPIA-Framework/sepia-stt-server/tree/dev) for SEPIA and would like to include LM building on Raspberry Pi.

I was wondering if it is possible to build OpenFST and Pynini wheels for Aarch64 and Armv7? :-)

**Comment by PierreAndreNoel** [comment]
@fquirin For Aarch64, you could try hacking the Dockerfile by starting `FROM quay.io/pypa/manylinux_2_24_aarch64 AS common` then iteratively fixing whatever breaks. You probably need some build flags for OpenFST and/or Pynini, but @kylebgorman and/or his documentation would know better than me.

**Comment by fquirin** [comment]
I feel comfortable trying to fix whatever breaks but if there are different build flags required I'm not really sure where to start :-/

**Comment by kylebgorman** [comment]
It's certainly possible platform-specific flags will be required but
honestly, I doubt it. OpenFst and friends are already running on mobile
devices all over the place...

**Comment by kylebgorman** [comment]
Going to close this but I'll be happy to take a look at a draft or PR.
