### ISSUE TITLE
Incompatibility with OpenFst 1.7.9?

### ISSUE THREAD

**Issue by lguo2020** [kylebgorman/pynini#29]
Looks like openfst 1.7.9 changed signature of GetFarType in fst/extentions/far/getters.h and I'm getting this compilation error when downloading pynini on top of openfst 1.7.9:

```
In file included from src/pywrapfst.cc:630:
/home/engshare/third-party2/openfst/1.7.9/platform007/ca4da3d/include/fst/extensions/far/getters.h:17:6: note: declared here
 bool GetFarType(const std::string &str, FarType *far_type);
      ^~~~~~~~~~
```

Is there a quick fix coming?

**Comment by kylebgorman** [comment]
Pynini is never compatible with more than one OpenFst release at a time. So, find the Pynini release that is compatible with OpenFst 1.7.9 and upgrade to it.

As the README here states, this is just a mirror that I update sporadically and can be used to submit bugs. You should actually obtain the release from `pynini.opengrm.org` or Conda (`conda install -c conda-forge pynini`).

(For reference the compatible version is Pynini 2.1.2, I believe.)
