### ISSUE TITLE
pip install fails because cython is imported in setup directly

### ISSUE THREAD

**Issue by bertsky** [kylebgorman/pynini#30]
When I install via `pip` from current master, I get this:

```
Collecting pynini@ git+https://github.com/kylebgorman/pynini.git#egg=pynini
  Cloning https://github.com/kylebgorman/pynini.git to /tmp/pip-install-477ckk7a/pynini
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-477ckk7a/pynini/setup.py'"'"'; __file__='"'"'/tmp/pip-install-477ckk7a/pynini/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vy_k3j1z
         cwd: /tmp/pip-install-477ckk7a/pynini/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-477ckk7a/pynini/setup.py", line 22, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

(I do not recall seeing this problem in the past, but maybe I did things differently then).

The cause is simple: setup.py tries to import `Cython` directly, before it gets the chance to follow `install_requires`. Traditionally, people have coped with this by all kinds of tricks (like calling the `pip` cmdline from setup). 

But there's good news: we can simply use [pyproject.toml](https://snarky.ca/what-the-heck-is-pyproject-toml) instead!

**Comment by bertsky** [comment]
> I am already running into #29 with 1.7.9 and cannot compile OpenFST 1.7.5 with recent g++ (`internal compiler error`) – so if you could upgrade this would help a lot.

correction: I cannot compile _pynini_ (both the version here and upstream) due to `internal compiler error`. So this is a completely independent issue (#31), and I should not wait for an update with my PR.

**Comment by cdeln** [comment]
Hi, the build system bootstrap with Cython and setuptools can now be solved with using pyproject.toml files.
See #62 for a fix.

**Comment by kylebgorman** [comment]
@ Alejandro this is a know issue and will be fixed in the next release, but the second error is unrelated.

**Comment by monim67** [comment]
Any update on this?

**Comment by kylebgorman** [comment]
It should be fixed by the migration to `pyproject.toml` in the next release. I can't make any promises when that'll be though I am working on it this fall. In the meantime, consider using one of the two sources for precompiled binaries of the library.

**Comment by kylebgorman** [comment]
Note to any readers: this is not platform-specific as far as I know.

**Comment by kylebgorman** [comment]
I put out a post-release because a lot of people were having trouble with this. I hope it solves the issue. It'll be on PyPI shortly.
