### ISSUE TITLE
compilation fails on GCC with internal compiler error

### ISSUE THREAD

**Issue by bertsky** [kylebgorman/pynini#31]
I am having difficulties comiling pynini – run via `pip install .` in the git working directory of the current version (after building+installing OpenFST 1.7.5) or source tarball of upstream 2.1.2 (after building+installing OpenFST 1.7.9).

Unfortunately, I **only** get this when running in a vanilla Ubuntu 18.04 container within a [CircleCI setup](https://github.com/bertsky/cor-asv-fst/blob/add-ci/.circleci/config.yml) (which uses [this makefile](https://github.com/bertsky/cor-asv-fst/blob/add-ci/Makefile) and is based on [this Docker image](https://github.com/OCR-D/core/blob/master/Dockerfile)). I cannot even reproduce this in a local Ubuntu 18.04 myself.

Here are the full logs:
- [compiling 2.1.0 with GCC 7.4.0](https://circleci.com/api/v1.1/project/github/bertsky/cor-asv-fst/8/output/104/0?file=true&allocation-id=5e1756b203d2d65822c65237-0-build%2FD276598)
- [compiling 2.1.2 with GCC 7.4.0](https://circleci.com/api/v1.1/project/github/bertsky/cor-asv-fst/20/output/104/0?file=true&allocation-id=5f418beb51f6284ba70b7fd7-0-build%2F6FCB0D65)
- [compiling 2.1.2 with GCC 7.5.0](https://circleci.com/api/v1.1/project/github/bertsky/cor-asv-fst/26/output/104/0?file=true&allocation-id=5f4237c853807853237c0041-0-build%2F500187BC)

Any help on how to approach this would be much appreciated.

**Comment by kylebgorman** [comment]
I'll upgrade what's mirrored here to 2.1.2, though as you mention that is not expected to help. In the past when I've seen this is really is perfectly good C++ code that somehow blows the stack of the compiler. 

I will assume this can be reproduced on certain platforms, but probably none of the ones I have sitting around.

**Comment by kylebgorman** [comment]
Upgrade to 2.1.2 is complete

**Comment by kylebgorman** [comment]
Going to close this from inactivity/can't replicate. CI build testing on Mac OS X and Linux is handled by Conda and that should detect this for most users, and also gets you around the need to build locally.
