### ISSUE TITLE
dot default SVG rendering broken

### ISSUE THREAD

**Issue by lxkain** [kylebgorman/pynini#35]
As of today, using the latest pynini and openFST sources, pip installs, and a base ubuntu 20.04, the default SVG rendering of graphviz's dot is broken. This is of course not pynini's fault, but it affects its output in jupyter notebooks. After much searching, I came upon a workaround that others might find useful:

```
import graphviz
from IPython.display import SVG, display
def draw(fst):
    fst.draw('tmp.dot', portrait=True, isymbols=fst.input_symbols(), osymbols=fst.output_symbols())
    graphviz.render('dot', 'svg', 'tmp.dot', renderer='cairo')
    return display(SVG(url='file:tmp.dot.cairo.svg'))
```

The key here is to use svg:cairo rendering. You can then use draw(fst). I wrote some code that tried to overwrite a fst object's _repr_svg_ function, but it's read-only, so for now I am using the functional version.

**Comment by kylebgorman** [comment]
Thanks Alex. Do you know what's broken?

I generally like the idea of moving the rendering from a command-line
shell-out to using the built-in graphviz, and maybe I ought to do that
anyways in the next release.

**Comment by lxkain** [comment]
If you remove the keyword argument `renderer` it will use the default SVG render (i.e. `dot -Tsvg`) which for some reason (I have not looked below this level) makes mistakes with the bounding box, resulting in wrongly sized and cropped outputs in notebooks.

**Comment by kylebgorman** [comment]
Actually, I don't think I want to use this approach in general because I
just read the source code for the graphviz PyPi package and it just uses
subprocess also, so there's no big improvement here. It seems like we just
need to add the Cairo renderer to the command used.

**Comment by lxkain** [comment]
I think that would do the trick until this is fixed in graphviz itself, agreed. Thank you again for continuing development on this package!

**Comment by lxkain** [comment]
Any developments on this front?

**Comment by kylebgorman** [comment]
Alright, so where we were is that we have nothing to gain from using the `graphviz` package but that we want it to use the Cairo renderer, is that right? One reason I didn't make any progress on this is I can't quickly replicate the issue, though if you're willing to try it out locally, that'd be sufficient for me to make the change for the next release.

So I think the format command should be `-Tcairo:svg`, is that your impression? That ought to mean that the renderer is Cairo and the format is SVG. If that's correct, you could take the current release, modify [this line](https://github.com/kylebgorman/pynini/blob/12587a4a3056931640dc741526225a0a5f02ca2f/extensions/_pywrapfst.pyx#L1580) to reflect, then recompile and test locally. Would you be willing to do that at some point?

**Comment by lxkain** [comment]
Absolutely, will do this shortly.

**Comment by kylebgorman** [comment]
Thanks so much. If you can confirm it works for you, I'll test to make sure
it doesn't make things worse for me locally, then I can push the change out.

**Comment by lxkain** [comment]
`-Tsvg:cairo` appears to have fixed the issue for me.

**Comment by kylebgorman** [comment]
Alright, I'll try myself and if it works it'll be in the next release.
Won't close this until I determine.

**Comment by kylebgorman** [comment]
Have determined this works, so I'll put it in the next release.
