### ISSUE TITLE
Numerical arc labels in Jupyter notebook

### ISSUE THREAD

**Issue by alumae** [kylebgorman/pynini#36]
I managed to install Pynini 2.1.3 on Google Colab. However, the arc labels in the displayed graphs are now all numerical (see attachment)

![Ekraanipilt 2021-02-08 14-09-14](https://user-images.githubusercontent.com/487640/107217936-99ad5e00-6a17-11eb-8809-2416e1fed2c2.png)

Expected: arcs with labels "a",  "a".

**Comment by kylebgorman** [comment]
Attach a symbol table to the FST using ‘set_input_symbols’ or
‘set_output_symbols’.

The reason we don’t do this automatically is that symbol tables have no
computational role to play at all: they’re purely for human display.
