### ISSUE TITLE
pynini no acceptor error

### ISSUE THREAD

**Issue by zhangsanfeng86** [kylebgorman/pynini#37]
Hi Kyle,

I get a error,as follow:

![image](https://user-images.githubusercontent.com/73547638/109906521-9dad6280-7cdb-11eb-8de4-bbbd95e9ab62.png)

**Comment by zhangsanfeng86** [comment]
I install pynini with "conda install -c conda-forge pynini"

**Comment by kylebgorman** [comment]
Hi! The function `acceptor` was renamed `accep` in Pynini 2.1.3. You can keep up with syntactic changes like this by reading the [`NEWS` file](http://www.opengrm.org/twiki/pub/GRM/PyniniDownload/NEWS) that we update with every release.

We made a lot of minor changes over the summer as we are wrapping up a monograph about Pynini...I don't anticipate too many other changes like this.

**Comment by zhangsanfeng86** [comment]
OK.
Thank you for ur reply.
