### ISSUE TITLE
Question: support for direct string-based regex->fst support

### ISSUE THREAD

**Issue by AdolfVonKleist** [kylebgorman/pynini#4]
I've been playing with this a bit and really liking it.  

One thing I am curious about and cannot seem to find in the docs or CLI help is whether or not it is possible to directly compile a compliant regular expression directly into an FSA?

I'm thinking something like:
```
import pynini

regex_fsa = pynini.acceptor ("^xyZ[1-3]+4$")
# Now regex_fsa can be used to match strings or compiled into a cascade
```

Is this possible without manually building up the individual expressions?

Apologies if this was better sent to the TWiki.

**Comment by kylebgorman** [comment]
No, there's no support for that kind of regexp syntax, at least not yet. We
could do a subset of that (basically everything except backtraces) though.

The one thing to note is that the edge delimiters "^" and "$" don't exist
in our world---though you can hallucinate them, say by appending "^" and
"$" to your input strings too, and there is [BOS] and [EOS] supported by
CDRewrite.

**Comment by jmcotelo** [comment]
I've been working in a project which kinda parses a subset of regex and builds FSA from it. I've managed to handle conversion of character classes (\w, \d, \s, etc...) in by using `string_map` over unicode codepoints.

My main concern is the common `/./` Is there other way of building an acceptor that consume any char without relying the same approach? Making a `string_map` on all possible codepoints seems a bit excessive to me.

Cheers, and i love this project :)

**Comment by kylebgorman** [comment]
Short answer, no, not without having some finite set $\Sigma$ that '.'
quantifies over. You could just restrict yourself to bytes, and then that
will work 99% of the time?

Thanks for your input and positive feedback! ;)
