### ISSUE TITLE
how to create empty FST

### ISSUE THREAD

**Issue by kalvinchang** [kylebgorman/pynini#40]
how can i create an empty FST with pynini without resorting to pywrapfst.Compiler().compile()

i've tried pynini.difference('', '') but this results in wacky behavior similar to the one in #12:

`pynini.compose('a', pynini.difference('', '').concat('a')).num_states() `
should be nonzero since 'a' should be accepted but returns 0

**Comment by kylebgorman** [comment]
Just use `pynini.Fst`.

**Comment by kalvinchang** [comment]
How can i create an empty FST that does accept the empty string?

```
fst = pynini.Fst()
s = fst.add_state()
fst.set_start(s)
fst.set_final(s)

fst.concat('a')
```
accepts 'a' as needed but also accepts the empty string

However, if I do not set s to be the final state, ```fst.concat('a')``` does not accept a as expected.

**Comment by kylebgorman** [comment]
Yeah, what you did there looks fine to me:

```def empty() -> pynini.Fst:
    f = pynini.Fst()
    s = fst.add_state()
    f.set_start(s)
    f.set_final(s)
    return f
```

The only alternative I see is `pynini.accep("")` or something like that. That should work though I kind of like the explicit approach taken above better.

**Comment by kalvinchang** [comment]
Thank you for your reply! I will keep that in mind. 
However, I miswrote, sorry!! I meant to ask: How can i create an empty FST that does NOT accept the empty string?

**Comment by kylebgorman** [comment]
`pynini.Fst()` does not accept an empty string, nor does, say `pynini.union("foo", "bar")`. I am not sure I understand your question though.

**Comment by kalvinchang** [comment]
I guess I wanted to create an empty FST that when concatenated to a nonempty FST, still accepts what it is supposed to accept. 
For example, 
```
empty = pynini.Fst()
empty.concat('a')
print(pynini.compose('a', empty).num_states()) # 0; does not accept 'a'
```

**Comment by kylebgorman** [comment]
> I guess I wanted to create an empty FST that when concatenated to a nonempty FST, still accepts what it is supposed to accept.

Can I ask: why?

**Comment by kalvinchang** [comment]
I am trying to convert (limited types of) regex to an FSA. For example, the regex "..*" should not accept empty strings. My current approach is to iterate through each symbol and concatenate the FSTs corresponding to each symbol. The FST that I start off with should not accept empty strings.

**Comment by kylebgorman** [comment]
The concatenation approach makes sense for me but you'll have the
special-case the creation of the "first" FST, as far as I see it. Instead
of concatenating it with a null FST you'll have to just use it as the root
FST.

**Comment by kalvinchang** [comment]
that makes sense. i will try that. thank you!
