### ISSUE TITLE
What is @ expresion?

### ISSUE THREAD

**Issue by anderleich** [kylebgorman/pynini#42]
Hi,
The title is self explanatory. What is the @ expresion used in the examples? Does it have an equivalent function?

For example:
`
_phi = (_pad_zeros @ _raw_factorizer @ _del_zeros @ _fix_teens).optimize()
`

**Comment by kylebgorman** [comment]
Yes, @ is the composition operator, chosen to resemble \circ. If you prefer
to, you can use the `pynini.compose`, which takes two FST arguments. It
also has additional optional arguments: you can disable connecting (i.e.,
trimming) the automaton after composition with `connect=False` (which can
be useful to debug a failed composition) or select a non-default
composition filter, which in certain circumstances can accelerate
composition (though this is a very advanced feature and may be dangerous).

K

**Comment by anderleich** [comment]
Perfect! Thanks!

**Comment by anderleich** [comment]
Say we have:
```python
_currencies = pynini.cross("$", "dollar")
_temperature = pynini.cross("ºC", "degress")
```

If I wanted to replace either currency or temperature from a string, what should I do?

if text is $ replace with dollar
if text is ºC replace with degress

`_currencies @ _temperature``gives an error because _temperature is not expecting a currency symbol.

Is it possible not to use `cdrewrite`?

**Comment by kylebgorman** [comment]
You need to embed both of them in a `cdrewrite`, then compose the two rewrite transducers together.

**Comment by anderleich** [comment]
I have a transducer to recognize numbers. I've embedded it in a `cdrewrite`. It seems to work just fine, but I've noticed a strange beharviour:

23 -> twenty three
2003 -> two thousand and three

but with two numbers

**23 2003 --> twenty three**
**23 asjkdhasj 2003 --> twenty three asjkdhasj**

with more numbers
2003 24 21 24,4 21 --> two thousand and three twenty four twenty one twenty four ,four twenty one
**2003 24 21 24,4 21 2003 --> empty**

I'm using `rewrite.one_top_rewrite` to obtain the best scoring string. I've tried `rewrite.top_rewrites` with the 10 best strings and none of them is just **twenty three**

**Comment by kylebgorman** [comment]
You've written the rule in a way that it can map 2003 to zero, or generally
doesn't have to verbalize the full number. I don't have the context to
determine how that's the case but I assume standard debugging procedure
will answer that question for you.

(This sort of application-specific debugging should probably be taken off
this forum, which is really just for reporting bugs or requesting new
features.)

>
