### ISSUE TITLE
Determining if a state is accepting

### ISSUE THREAD

**Issue by kalvinchang** [kylebgorman/pynini#45]
Currently, I am determining if a state is an accepting state with the following:
```fsa.final(state) == pynini.Weight.one('tropical')```

However, this approach is flawed if we set the weight of a state to 1. Is there a better way of figuring out if a state is accepting or not?

**Comment by kylebgorman** [comment]
Why not just:

```python
def accepting(fst: pynini.Fst) -> bool:
    return fst.final(state) != pynini.Weight.zero(fst.arc_type())
```

?

**Comment by kalvinchang** [comment]
oh that works too. Thanks!!
