### ISSUE TITLE
cross don't have a weight parameter like transducer?

### ISSUE THREAD

**Issue by npuichigo** [kylebgorman/pynini#48]
These lines are inconsistent.

https://github.com/kylebgorman/pynini/blob/a573bb49a4f307f5e920570e45d517065bd2b7cc/pynini/__init__.pyi#L129

https://github.com/kylebgorman/pynini/blob/a573bb49a4f307f5e920570e45d517065bd2b7cc/extensions/_pynini.pyx#L905

**Comment by kylebgorman** [comment]
Thanks for report, you're right. Fixed in next release (testing internally as we speak). I'll leave the bug open until that's out.
