### ISSUE TITLE
Cannot install on macOS M1

### ISSUE THREAD

**Issue by stefanocoretta** [kylebgorman/pynini#50]
Hi! I tried to install pynini on macOS 12.0.1 ARM with mini-forge, but there is no build for this architecture.

I tried to install from source, but it seems that OpenFst is not available either. I am trying now to install OpenFst from source, will update soon.

EDIT: Nope, it failed while installing, although it seems like a permission issue.

```bash
libtool: install: /opt/homebrew/bin/ginstall -c .libs/fstarcsort /usr/local/bin/fstarcsort
ginstall: cannot create regular file '/usr/local/bin/fstarcsort': Permission denied
make[3]: *** [install-binPROGRAMS] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by kylebgorman** [comment]
Source installation is the only option except for:

* On non-Windows platforms that support Conda, there are high-quality packages available from conda-forge. 
* On Linux x86_64 there is a binary wheel available.

Try installing with `sudo`? Or this could be something to do with Homebrew, which I don't command.

I would be happy to make binary wheels available for other platforms but I would need a volunteer to modify the Docker setup I use to make the Linux one.

**Comment by stefanocoretta** [comment]
Hi! Thanks, eventually I just installed full anaconda with home brew and things work fine now.

It might be something related to the brewed version of miniconda and miniforge. A friend has installed miniconda from the official binaries and didn't have this issue.
