### ISSUE TITLE
programmatic matching -- doc question

### ISSUE THREAD

**Issue by funderburkjim** [kylebgorman/Pynini#6]
This question based on the 'sheep' example:
```
sheep = acceptor("b") + acceptor("a").plus
sheep.optimize(True)
```
Is there an 'official' programmatic way to test whether a given string 's' matches  the 'regular expression'
specified by 'sheep'?
By trial and error, my candidate expression is:
```
compose(s,sheep).num_states() != 0
```

**Comment by kylebgorman** [comment]
Good question. That one works just fine. An even more general version,
which works with the lower level `pywrapfst` layer, is:

    compose(s, sheep).start() == NO_STATE_ID

The built-in function `matches` is a two-argument function that does
exactly this.

Also just FYI, you can pass a string in place of an acceptor and Pynini
will implicitly compile it into an acceptor for you.

**Comment by taufique74** [comment]
What would be the appropriate match() function for version >= `2.1.3` ?
I'm currently using the `python.lib.rewrite.matches()` function this way
```python
from pynini.lib.rewrite import matches

fst = pynini.accep('abc')

input_string = 'abc '
matches(input_string, fst, input_string) # True

input_string = 'abcd '
matches(input_string, fst, input_string) # False
```
Does this look okay?

**Comment by kylebgorman** [comment]
I think you want:

    matches(input_string, input_string, fst)

The rule is supposed to be the third argument.

**Comment by taufique74** [comment]
Yeah, you're right! My bad!
Thanks so much for the clarification.
