### ISSUE TITLE
Cannot install pynini==2.1.5 via pip

### ISSUE THREAD

**Issue by sj-h4** [kylebgorman/pynini#80]
Hi, there. Thank you for your great job.
I am encountering an error even though Cython is installed. I use Linux (x86-64). The error message is:

`ModuleNotFoundError: No module named 'Cython'`

How do I solve this problem?

**Comment by kylebgorman** [comment]
As is documented here, this was an issue with the v2.1.5 release. There is a release 2.1.5.post2 if you really need the 2.1.5 feature set. We are currently on version 2.1.6, though, and you probably want that one instead. 

If you're on x86-64 Linux though why bother compiling from scratch? We ship a precompiled version for that platform. Run `pip install --only-binary :all: pynini==2.1.5.post1` if you need 2.1.5 features or `pip install --only-binary :all: pynini` if you just want the newest version. Or, if you use Conda you can install these like `conda install -c conda-forge pynini` etc.

**Comment by ztxdcyy** [comment]
可能你的机器是arm架构的，pynini目前只有基于x86预编译的轮子，你可能需要自己下载源码并编译（注意开启虚拟环境）

**Comment by zslefour** [comment]
How to compile under windows, please.

**Comment by 3550292587** [comment]
> How to compile under windows, please.

如果是在windows中安装，我在这里找到了已经编译好的wheel,但是版本是2.1.6
https://github.com/billwuhao/pynini-windows-wheels/releases/tag/v2.1.6.post1
下面的README.MD文件中有相关安装教程
https://github.com/billwuhao/ComfyUI_IndexTTS?tab=readme-ov-file

**Comment by kylebgorman** [comment]
Install via Conda-Forge. We don’t support Windows otherwise. It’s documented in the README.

**Comment by 3550292587** [comment]
> Install via Conda-Forge. We don’t support Windows otherwise. It’s documented in the README.On Sep 19, 2025, at 8:57 AM, Xiao ***@***.***> wrote:﻿3550292587 left a comment ([kylebgorman/pynini#80](https://github.com/kylebgorman/pynini/issues/80))
> 
> How to compile under windows, please.
> 
> 如果是在windows中安装，我在这里找到了已经编译好的wheel,但是版本是2.1.6
> https://github.com/billwuhao/pynini-windows-wheels/releases/tag/v2.1.6.post1
> 下面的README.MD文件中有相关安装教程
> https://github.com/billwuhao/ComfyUI_IndexTTS?tab=readme-ov-file
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

下面这个是从源码编译，我没有尝试过，你可以试试https://github.com/SystemPanic/pynini-windows

**Comment by zslefour** [comment]
> > How to compile under windows, please.
> 
> 如果是在windows中安装，我在这里找到了已经编译好的wheel,但是版本是2.1.6 https://github.com/billwuhao/pynini-windows-wheels/releases/tag/v2.1.6.post1 下面的README.MD文件中有相关安装教程 https://github.com/billwuhao/ComfyUI_IndexTTS?tab=readme-ov-file

谢谢。我先是使用Miniconda构建虚拟环境安装了，然后9月安装indextts是也发现了这个wheel。

**Comment by zslefour** [comment]
> Install via Conda-Forge. We don’t support Windows otherwise. It’s documented in the README.

Thanks，I have done it this way.
