### ISSUE TITLE
Command line error D8021 : invalid numeric argument '/Wno-register'

### ISSUE THREAD

**Issue by frankinstien111** [kylebgorman/pynini#85]
I'm getting this error when installing requirements for AnyGPT on Windows 11. It appears as a flag problem with MSVC, not sure what to do, maybe use a lower version, I have visual studio 2022 and 2019. Any ideas?

` copying pynini\lib\BUILD.bazel -> build\lib.win-amd64-cpython-39\pynini\lib
      copying pynini\lib\py.typed -> build\lib.win-amd64-cpython-39\pynini\lib
      running build_ext
      building '_pywrapfst' extension
      creating build\temp.win-amd64-cpython-39\Release\extensions
      "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Frank\miniconda3\envs\AnyGPT\include -IC:\Users\Frank\miniconda3\envs\AnyGPT\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpextensions/_pywrapfst.cpp /Fobuild\temp.win-amd64-cpython-39\Release\extensions/_pywrapfst.obj -std=c++17 -Wno-register -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char
      cl : Command line error D8021 : invalid numeric argument '/Wno-register'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pynini
Failed to build pynini
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pynini)
`

**Comment by kylebgorman** [comment]
Hi @frankinstien111 I must confess I don't know the first thing about Windows development (I use WSL, exclusively, when I work on Windows).

We distribute a pre-compiled Pynini for 64-bit Windows, developed by @mmcauliffe, via Conda-Forge, but that's the extent of our Windows support. (If you use Conda, the command is just `conda install -c conda-forge pynini`.)

**Comment by frankinstien111** [comment]
Thx, that worked.

**Comment by kylebgorman** [comment]
I'll close this then.

**Comment by AmadeussSystem** [comment]
conda install -c conda-forge pynini i tried this and this doesnt works

**Comment by kylebgorman** [comment]
Hi @AmadeussSystem start a new issue---but you'll need to give more information: what platform and what was the message you're seeing? Please don't "necrobump" a long-closed issue with something that might be unrelated.
