### ISSUE TITLE
What is the correct epsilon handling in manually constructed symbol tables?

### ISSUE THREAD

**Issue by wrznr** [kylebgorman/Pynini#9]
Depicting the following simple transduction,
```python
test = pynini.transducer("a", pynini.string_map(["a","b","c"]))
```
results in:
![debug2](https://user-images.githubusercontent.com/26707219/48278203-23db7600-e44d-11e8-9cdd-c70a9badd143.png)

Using a pre-defined symbol table however,
```python
test = pynini.transducer("a", pynini.string_map(["a","b","c"], input_token_type=symbol_table, output_token_type=symbol_table), input_token_type=symbol_table, output_token_type=symbol_table)
```
results in:
![debug](https://user-images.githubusercontent.com/26707219/48278297-6dc45c00-e44d-11e8-88f7-1c1efba13e34.png)

The symbol table consequently does not contain `<epsilon>` and `!` is mapped onto 0:
```python
print(syms.member("<epsilon>")) # False
print(syms.member("!")) # True
print(syms.find("!")) # 0
```
It is constructed in [this function](https://github.com/wrznr/timur/blob/9ec9b1105e5d778ee71dbaf49da865f0afb90cd9/timur/helpers/helpers.py#L22).

Since `!` is the first symbol added to the symbol table, the behavior somehow makes sense. But shouldn't epsilon be a reserved, specially treated symbol? What am I missing?

**Comment by wrznr** [comment]
Thanks for your hints. Manually adding `<epsilon>` as the first symbol did the trick: I had a number of tranducers containing both `<epsilon>` and `!` (most probably through symbol table merging), which had a rather weird structure after optimization. Now, they are optimized correctly! (I am really looking forward to the global symbol handling option.)

**Comment by kylebgorman** [comment]
All the pieces are now ready for releasing that, I believe.

I am traveling this week and away from the computer with the needed 2FA but
I will be back at it on Friday. Will ping this thread then.
